dependency:
  files:
    - pom.xml
  black-list:
    - groupId: junit
    - groupId: com.rabbitpre.tubit
      artifactId: tubit-orm-spring-boot-starter
      version:
    - groupId: com.alibaba
      artifactId: fastjson
      version: